// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzzM0F8zlyaFDbG6QB340MLU_MUwKf-uM',
    appId: '1:980828865246:web:8747c976b0cc53fddab84f',
    messagingSenderId: '980828865246',
    projectId: 'flutter-prep-47c99',
    authDomain: 'flutter-prep-47c99.firebaseapp.com',
    databaseURL: 'https://flutter-prep-47c99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-47c99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeO3ltLHsJEEBd5bYUvkz14CiJNXykNm8',
    appId: '1:980828865246:android:8a184d99cb381c06dab84f',
    messagingSenderId: '980828865246',
    projectId: 'flutter-prep-47c99',
    databaseURL: 'https://flutter-prep-47c99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-47c99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0s_whnWYrenApkzQU6OjnfW6Ni_mY9YA',
    appId: '1:980828865246:ios:6c9d62d5801b87aedab84f',
    messagingSenderId: '980828865246',
    projectId: 'flutter-prep-47c99',
    databaseURL: 'https://flutter-prep-47c99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-47c99.appspot.com',
    iosBundleId: 'com.example.secureRideHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0s_whnWYrenApkzQU6OjnfW6Ni_mY9YA',
    appId: '1:980828865246:ios:65be01e69e0fca07dab84f',
    messagingSenderId: '980828865246',
    projectId: 'flutter-prep-47c99',
    databaseURL: 'https://flutter-prep-47c99-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-prep-47c99.appspot.com',
    iosBundleId: 'com.example.secureRideHome.RunnerTests',
  );
}
